branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE
  - PKG_CFLAGS="-O3 -Wall -pedantic"

language: r
sudo: required
cache: packages
cran: http://cran.rstudio.com
warnings_are_errors: true
r_build_args: ''
r_check_args: '--no-build-vignettes'

r:
  - release
  - devel

addons:
  apt:
    packages:
    - libnlopt-dev

r_packages:
  - data.table
  - devtools
  - covr
  - sessioninfo
  - delayed
  - origami

r_github_packages:
  - r-lib/sessioninfo
  - r-lib/covr
  - tlverse/sl3

after_success:
  - travis_wait 80 Rscript -e 'covr::codecov()'

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change
